# Unit 1: Introduction to Numerical Computation & Python Basics
**Date:** Jan 15 (Thursday)

**Topic:** Numpy arrays, Data types, Precision

## 1. Introduction
Numerical computation involves solving mathematical problems by representing numbers as approximations (floating-point arithmetic) rather than exact symbolic expressions. In this course, we use **Python** and specifically the library **NumPy** (*Numerical Python*) because it is highly optimized for vector and matrix operations.

### Why NumPy over Lists?
* **Performance:** NumPy arrays are stored in contiguous memory blocks.
* **Functionality:** Built-in linear algebra, Fourier transforms, and random number capabilities.
* **Syntax:** Mathematical operations apply element-wise automatically.

In [2]:
import numpy as np

# A standard Python list
py_list = [1, 2, 3, 4, 5]

# Creating a NumPy array
np_arr = np.array(py_list)

print(f"Python List: {py_list}")
print(f"NumPy Array: {np_arr}")
print(f"Type of np_arr: {type(np_arr)}")

Python List: [1, 2, 3, 4, 5]
NumPy Array: [1 2 3 4 5]
Type of np_arr: <class 'numpy.ndarray'>


## 2. Creating Arrays
We rarely type out arrays manually in numerical physics. Instead, we generate them using functions like `arange`, `linspace`, or `zeros`.

* `np.arange(start, stop, step)`: Like Python's `range` but returns an array.
* `np.linspace(start, stop, num)`: Generates `num` points evenly spaced between `start` and `stop` (Crucial for plotting and grids).
* `np.zeros(N)` / `np.ones(N)`: Creates arrays filled with 0s or 1s.

In [14]:
# Create an array of integers from 0 to 9
arr_range = np.arange(0, 10, 1.3)
print(f"Arange: {arr_range}")

print(type(arr_range))
print(arr_range.shape)

print(arr_range.reshape(4,-1).T)



Arange: [0.  1.3 2.6 3.9 5.2 6.5 7.8 9.1]
<class 'numpy.ndarray'>
(8,)
[[0.  2.6 5.2 7.8]
 [1.3 3.9 6.5 9.1]]


In [15]:
# Create an array of integers from 0 to 9
arr_range = np.arange(0, 10, 1.3)
print(f"Arange: {arr_range}")

# Create 11 points between 0 and 1 (inclusive)
# This is very useful for x-axes in plots
arr_lin = np.linspace(0, 1, 11)
print(f"Linspace: {arr_lin}")

# Create a 3x3 matrix of zeros
arr_zeros = np.zeros((4, 4))
print(f"Zeros Matrix:\n{arr_zeros}")

Arange: [0.  1.3 2.6 3.9 5.2 6.5 7.8 9.1]
Linspace: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
Zeros Matrix:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
arr_zeros[0][0] = 2.0
arr_zeros[2][2] = 5.0
arr_zeros

array([[2., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 5., 0.],
       [0., 0., 0., 0.]])

In [29]:
matrix = [[1, 4, 5] , [2, 8 , 6],  [5, 4, 7]]
# print(matrix + [1.2])

# print(type(matrix))

matrix = np.array(matrix)

# print(matrix_numpy + 1.2)


print(type(matrix))




<class 'numpy.ndarray'>


## 3. Data Types
Unlike Python lists, a NumPy array must contain data of the **same type**. This allows the computer to optimize memory usage. Common types in physics:

* `int32` / `int64`: Integers
* `float32` / `float64`: Floating point numbers (decimals)
* `complex128`: Complex numbers ($a + bi$)

In [30]:
# Integer array
int_arr = np.array([1, 2, 3], dtype=np.int64)
print(f"Integer Array dtype: {int_arr.dtype}")

# Float array (Standard for scientific computing)
float_arr = np.array([1., 2., 3.], dtype=np.float64)
print(f"Float Array dtype: {float_arr.dtype}")

# Complex array
complex_arr = np.array([1+2j, 3+4j])
print(f"Complex Array:\n{complex_arr}")
print(f"Real part: {complex_arr.real}")
print(f"Imaginary part: {complex_arr.imag}")

Integer Array dtype: int64
Float Array dtype: float64
Complex Array:
[1.+2.j 3.+4.j]
Real part: [1. 3.]
Imaginary part: [2. 4.]


## 4. Precision and Floating Point Arithmetic
Computers cannot store infinite precision. They store numbers in scientific notation (binary).
* **Machine Epsilon:** The smallest difference between $1.0$ and the next representable floating-point number.
* **Round-off Error:** The error introduced when a number cannot be exactly represented.

**Key Example:** $0.1 + 0.2$ often does not equal exactly $0.3$ in floating point arithmetic.

In [32]:
# The classic floating point issue
val = 0.1 + 0.2
print(val)
print(f"0.1 + 0.2 = {val:.4f}")
print(f"Is it exactly 0.3? {val == 0.3}")

# Checking Machine Epsilon for standard float (64-bit)
# This is the 'resolution' of our number system
eps = np.finfo(float).eps
print(f"\nMachine Epsilon (float64): {eps}")

# Comparing 32-bit vs 64-bit precision
# Notice how 32-bit loses accuracy faster
float32_eps = np.finfo(np.float32).eps
print(f"Machine Epsilon (float32): {float32_eps}")

0.30000000000000004
0.1 + 0.2 = 0.3000
Is it exactly 0.3? False

Machine Epsilon (float64): 2.220446049250313e-16
Machine Epsilon (float32): 1.1920928955078125e-07


In [38]:
0.1+0.3

0.4

### Summary of Day 1
1.  **Arrays:** We use `numpy.array` for fast math.
2.  **Generation:** Use `linspace` for grids, `zeros` for initialization.
3.  **Types:** Be aware of `int` vs `float`. If you divide integers, Python 3 gives a float, but older systems might truncate.
4.  **Precision:** Never check if two floats are `==`. Always check if they are "close enough" using `np.isclose()` or `abs(a - b) < tolerance`.

# Practice: Unit 1 (Numpy Basics)
**Instructions:**
1.  Look for the `# TODO` comments in the code blocks.
2.  Replace the `______` or incomplete lines with the correct code.
3.  Run the cell. If you see an `AssertionError`, your answer is incorrect.
4.  If you see **"Success!"**, move to the next problem.

## Problem 1: The Grid Challenge
**Goal:** Create two identical time arrays using different methods.
* `t_1`: Use `arange`. (Careful: `arange` excludes the stop value!)
* `t_2`: Use `linspace`.
* Target: Start=0, Stop=10, Step=0.5 (Total 21 points).

In [ ]:
import numpy as np

# --- STUDENT SECTION ---
# TODO: Fix the stop value in arange to ensure it includes 10.0
# Hint: If step is 0.5, what should the stop be to include 10?
t_1 = np.arange(start=0, stop=______, step=0.5)

# TODO: Calculate how many points are needed for 0 to 10 with 0.5 steps
# Hint: (10 - 0) / 0.5 + 1
num_points = ______
t_2 = np.linspace(0, 10, int(num_points))

# --- AUTO-GRADER (DO NOT EDIT) ---
print(f"t_1 shape: {t_1.shape}")
print(f"t_2 shape: {t_2.shape}")

assert len(t_1) == 21, f"t_1 has {len(t_1)} points, expected 21. Check your stop value."
assert len(t_2) == 21, f"t_2 has {len(t_2)} points, expected 21. Check num_points."
assert np.allclose(t_1, t_2), "Arrays do not match! Check your start/stop logic."
print("\n✅ Success! Both arrays are identical.")

## Problem 2: Vectorization vs. Loops
**Goal:** Calculate the position $y(t) = v_0 t - 0.5 g t^2$ without using a loop.
The loop version is provided but is slow. You must implement the "Vectorized" version.

In [53]:
# araay_ = np.array([2, 4, 8])


# for i in np.linspace(1, 10, 51):
#   print(i)
#   a = i//1
#   print(a)




In [40]:
# Constants
v0 = 50.0 # m/s
g  = 9.81 # m/s^2
t  = np.linspace(0, 10, 1000)

# 1. SLOW WAY (Loop) - Already done for you
y_loop = []
for time_val in t:
    val = v0 * time_val - 0.5 * g * (time_val ** 2)
    y_loop.append(val)
y_loop = np.array(y_loop)

# 2. FAST WAY (Vectorized)
# TODO: Write the equation once using the array 't'.
# Do NOT use a loop. The math applies to the whole array at once.
y_vec = ______

# --- AUTO-GRADER ---
assert y_vec is not None, "You haven't assigned a value to y_vec!"
diff = np.max(np.abs(y_loop - y_vec))
assert diff < 1e-9, f"Vectorized calculation differs from loop! Max diff: {diff}"

print(f"Loop first value: {y_loop[0]}")
print(f"Vec  first value: {y_vec[0]}")
print("\n✅ Success! Vectorization works.")

NameError: name '______' is not defined

## Problem 3: The "Integer Trap" Debugging
**Goal:** A student tried to create a matrix to store probability values (decimals between 0 and 1), but all their numbers are turning into zeros.
**Task:** Identify the bug in the initialization line and fix it.

In [ ]:
# --- BROKEN CODE ---
# The student wants a 3x3 matrix.
# They try to set the middle value to 0.5, but it prints 0. Why?
# TODO: Change the dtype in the line below to fix the bug.
prob_matrix = np.zeros((3, 3), dtype=np.int32)

prob_matrix[1, 1] = 0.5

print("Matrix:\n", prob_matrix)

# --- AUTO-GRADER ---
assert prob_matrix[1, 1] == 0.5, "The middle value is not 0.5! Did you fix the dtype?"
print("\n✅ Success! The matrix can now hold decimals.")

## Problem 4: Floating Point Detective
**Goal:** Find the smallest integer `N` such that adding `1.0 / (10**N)` to `1.0` results in `1.0` due to precision loss.
This demonstrates the limits of 64-bit floating point numbers.

In [ ]:
# --- STUDENT SECTION ---
# Run this loop mentally or experimentally to find where the computer "gives up".
# Change N until the assertion PASSES.

# TODO: Guess the integer N where the computer loses precision.
# Try 5, then 10, then 15, then 16...
N = ______

epsilon_attempt = 1.0 / (10.0**N)
result = 1.0 + epsilon_attempt

print(f"1.0 + 1e-{N} = {result:.20f}")

# --- AUTO-GRADER ---
# We want to find the case where adding epsilon makes NO difference.
if result == 1.0:
    print(f"\n✅ Success! At 10^-{N}, the computer thinks the number is just 1.0.")
else:
    print(f"\n❌ Not quite. The computer can still 'see' the difference. Try a larger N.")
    # This ensures the student keeps trying until they hit the limit
    assert result == 1.0